GET http://localhost:5000


### Check Server Status
GET http://localhost:5000/api


### Register User / SignUp
POST http://localhost:5000/api/users/register
Content-Type: application/json

{
    "name": "Test User",
    "email": "test@test.com",
    "password": "test"
}


### Login User / SignIn
POST http://localhost:5000/api/users/login
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "test"
}


### Get User Profile
GET http://localhost:5000/api/users/profile
Authorization: 


### Update User Profile
PATCH http://localhost:5000/api/users/profile
Authorization: 
Content-Type: application/json

{
    "name": "Test Name",
    "email": "test@test.com"
}


### Update User Password / Change User Password
PATCH http://localhost:5000/api/users/password
Authorization: 
Content-Type: application/json

{
    "oldPassword": "test",
    "newPassword": "password"
}


### Get All Tasks
GET http://localhost:5000/api/tasks
Authorization: 


### Get Single Task
GET http://localhost:5000/api/tasks/5eccda38d0083006a810c0d0
Authorization: 


### Create Task / Add Task
POST http://localhost:5000/api/tasks
Authorization: 
Content-Type: application/json

{
    "description": "Test Task 1",
    "label": "Others",
    "dueDate": "2020-05-30"
}


### Change Status
PATCH http://localhost:5000/api/tasks/5eccda38d0083006a810c0d0
Authorization: 


### Delete Task / Remove Task
DELETE http://localhost:5000/api/tasks/5eccda38d0083006a810c0d0
Authorization: 


###
